export const RULE_VERSION='2.6.0';
export const REGION_DISTRICTS={'Москва':'ЦФО','Московская область':'ЦФО','Санкт-Петербург':'СЗФО','Томская область':'СФО','Свердловская область':'УФО','Ставропольский край':'СКФО','Республика Татарстан':'ПФО'};
export const norm=s=>String(s??'').toLowerCase().replaceAll('ё','е').replace(/[^a-zа-я0-9.\s]/g,' ').replace(/\s+/g,' ').trim();
export const THEMES=[['IT и цифровые технологии','программ код разработ информат компьютер искусствен интеллект анализ данных аналитик python тестиров цифров','09 10 01 02'],['Право и управление','управлен руковод менеджмент проект юрид юрист прав кадр эконом логист бухгалтер финанс','38 40 41'],['Образование и гуманитарные','социальн психолог помощ людям педагог учител образован дизайн творчеств музы культур язык туризм гостиниц','37 39 42 43 44 45 46 47 48 49 50 51 52 53 54 55'],['Здравоохранение','медицин врач сестрин стомат реабилитац лечебн','30 31 32 33 34'],['Машиностроение','станок производств инженер оборудован машиностро робот техник ремонт','15 22 27 28 29'],['Строительство и архитектура','строител архитектур геодез кадастр','07 08 21'],['Транспорт и БПЛА','транспорт автомобил авиаци бпла беспилот дрон','23 24 25 26'],['Энергетика и электросети','энергет электр сети радиотех связ','11 12 13 14'],['Агро и пищевые технологии','агро аграр пищев экологи природ биолог хим биотех ветеринар','04 05 06 18 19 35 36'],['Нефтегазовая промышленность','нефт газ бурени','']];
export function themeOf(p){const code=p.code?.split('.')[0];return THEMES.find(t=>code&&t[2].split(' ').includes(code))?.[0]||signals(p.title+' '+(p.profile||''))[0]||'Образование и гуманитарные'}
export function signals(text){const t=norm(text);return THEMES.filter(([,words])=>words.split(' ').filter(w=>w.length>2).some(w=>t.includes(w))).map(x=>x[0])}
const searchIndex=new WeakMap();
export function matchesQuery(p,q){const words=norm(q).split(' ').filter(Boolean);if(!words.length)return true;let hay=searchIndex.get(p);if(hay===undefined){hay=norm([p.title,p.profile,p.institution,p.shortName,p.code,p.city,p.region,p.theme,...(p.keywords||[])].join(' '));searchIndex.set(p,hay)}return words.every(w=>hay.includes(w))}
export function filterCatalog(programs,f={}){return programs.filter(p=>matchesQuery(p,f.query)&&(!f.level||p.level===f.level)&&(!f.region||p.region===f.region)&&(!f.city||p.city===f.city)&&(!f.district||p.district===f.district)&&(!f.theme||p.theme===f.theme)&&(!f.institution||p.institution===f.institution)&&(!f.recordType||p.recordType===f.recordType)&&(!f.rgsu||p.rgsu)&&(!f.format||hasFormat(p,f.format))&&(!f.budget||p.budgetPlaces>0)&&(!f.maxPrice||(Number.isFinite(p.priceFrom)&&p.priceFrom<=Number(f.maxPrice)))&&(!f.maxMonths||(durationMonths(p,f.format)!==null&&durationMonths(p,f.format)<=Number(f.maxMonths)))&&(!f.complete||(p.formats&&p.duration&&Number.isFinite(p.priceFrom)&&Number.isFinite(p.budgetPlaces))))}
export function hasFormat(p,f){if(f==='Онлайн без посещений')return p.remoteFull===true;const vals=(p.formats||'').toLowerCase().split(/[,/]/).map(s=>s.trim());if(f==='С дистанционными технологиями')return vals.some(s=>s.includes('дистанц'));return vals.some(value=>{const base=value.match(/^(очно-заочная|заочная|очная)(?:\s|$)/)?.[1];return base===f.toLowerCase()})}
export function durationMonths(p,format='',education=''){if(p.variants?.length&&(format||education)){const variants=p.variants.filter(v=>(!format||hasFormat(v,format))&&(!['nine','school'].includes(education)||!v.admissionBases?.length||v.admissionBases.includes(education)));if(variants.length){const values=variants.map(v=>durationMonths({duration:v.duration}));const known=values.filter(v=>v!==null);return known.length===values.length&&new Set(known).size===1?known[0]:null}}const text=String(p.duration||'').trim().toLowerCase();const exact=text.match(/^(?:(\d+(?:[.,]\d+)?)\s*(?:год(?:а)?|лет)\s*)?(?:(\d+)\s*(?:месяц(?:а|ев)?|мес\.?)\s*)?$/);if(!exact||(!exact[1]&&!exact[2]))return null;const value=Number((exact[1]||'0').replace(',','.'))*12+Number(exact[2]||0);return Number.isInteger(value)&&value>0?value:null}
const educationLevels={nine:['СПО'],school:['СПО','Бакалавриат','Специалитет'],spo:['СПО','Бакалавриат','Специалитет','ДПО'],bachelor:['СПО','Бакалавриат','Специалитет','Магистратура','ДПО'],master:['СПО','Бакалавриат','Специалитет','Магистратура','Аспирантура','ДПО']};
export function recommend(programs,profile,{limit=6,uncertainLimit=3}={}){const allowed=educationLevels[profile.education];if(!allowed)return {status:'clarify',items:[],uncertain:[],excluded:0,message:'Уточните завершённый уровень образования. Без него нельзя проверить базовые условия подбора.'};
const topics=profile.themes||signals(profile.request+' '+profile.experience),eligible=[],uncertain=[];let excluded=0;
for(const p of programs){if(p.verification!=='source'||!allowed.includes(p.level)){excluded++;continue}if(profile.district&&p.district!==profile.district){excluded++;continue}if(profile.region&&p.region!==profile.region){excluded++;continue}if(profile.education==='nine'&&p.level==='СПО'&&p.admissionBases?.length&&!p.admissionBases.includes('nine')){excluded++;continue}if(profile.format&&p.formats&&!hasFormat(p,profile.format)){excluded++;continue}if(profile.format==='Онлайн без посещений'&&p.remoteFull!==true){excluded++;continue}const months=durationMonths(p,profile.format,profile.education);const minimumMonths=durationMonths({...p,duration:p.duration?.replace(/^от\s+/i,'')});if(profile.maxMonths&&(months??minimumMonths)!==null&&(months??minimumMonths)>Number(profile.maxMonths)){excluded++;continue}if(profile.budget&&p.budgetPlaces===0){excluded++;continue}
const unknown=[];if(profile.education==='nine'&&!p.admissionBases?.includes('nine'))unknown.push('приём на базе 9 классов');if(p.specialConditions)unknown.push('специальные условия отбора');if(profile.format&&!p.formats)unknown.push('форма обучения');if(profile.maxMonths&&months===null)unknown.push('точный срок обучения');if(profile.budget&&!(p.budgetPlaces>0))unknown.push('бюджетные места');if(profile.budget&&profile.format&&!p.budgetByFormat?.[profile.format])unknown.push('бюджет по выбранной форме');
const text=norm(p.title+' '+p.profile);let score=topics.includes(p.theme)?12:0;const tokens=norm(profile.request+' '+profile.experience).split(' ').filter(w=>w.length>3);const hits=[...new Set(tokens.filter(w=>text.includes(w.slice(0,Math.max(4,w.length-2)))))];score+=Math.min(hits.length*4,20);if(topics.length&&score===0){excluded++;continue}const reasons=[];if(topics.includes(p.theme))reasons.push('Выбрано направление «'+p.theme+'»');if(hits.length)reasons.push('Есть совпадения с вашим описанием: '+hits.slice(0,3).join(', '));if(profile.format)reasons.push('В источнике указана выбранная форма');if(profile.district)reasons.push('В выбранном федеральном округе');if(profile.region)reasons.push('Регион: '+profile.region);if(profile.goal==='fast'&&p.level==='ДПО'){score+=6;reasons.push('Программа дополнительного образования')}if(profile.goal==='continue'&&((profile.education==='bachelor'&&p.level==='Магистратура')||(profile.education==='master'&&p.level==='Аспирантура'))){score+=6;reasons.push('Следующая ступень образования')}if(!reasons.length)reasons.push('Вариант для знакомства с каталогом');const item={program:p,score,reasons,unknown};(unknown.length?uncertain:eligible).push(item)}
const sort=(a,b)=>b.score-a.score||Number(b.program.rgsu)-Number(a.program.rgsu)||a.program.title.localeCompare(b.program.title,'ru');eligible.sort(sort);uncertain.sort(sort);
return {status:eligible.length?'ok':'empty',items:eligible.slice(0,limit),uncertain:uncertain.slice(0,uncertainLimit),total:eligible.length,uncertainTotal:uncertain.length,excluded,topics,message:eligible.length?'Предварительные варианты по вашему профилю':'Программ с подтверждённым соответствием всем заданным условиям пока нет.'}}
